# Generated by Django 4.2.7 on 2025-06-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = []
