# Generated by Django 4.2.7 on 2025-06-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_auto_20250605_1522"),
    ]

    operations = []
