# Generated by Django 4.2.7 on 2025-06-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_auto_20250605_1524"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Может отменять публикацию продукта"),
                    ("can_change_publish_status", "Может изменять статус публикации"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
