# Generated by Django 4.2.7 on 2025-06-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="publish_status",
            field=models.CharField(
                choices=[
                    ("published", "Опубликовано"),
                    ("moderation", "На модерации"),
                    ("rejected", "Отклонено"),
                ],
                default="moderation",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
